<style>
  @import url('https://fonts.googleapis.com/css2?family=Dancing+Script&display=swap');

  nav {
    background-image: url(../img/nav1.png);
  }

  body .wrapper .container h1 {
    font-family: 'Dancing Script', serif;
    color: darkcyan;
  }

  body {
    margin-top: 3rem;
  }

  i {
    font-size: 18px;
  }

  .color-change-2x {
    -webkit-animation: color-change-2x 2s linear infinite alternate both;
    animation: color-change-2x 2s linear infinite alternate both
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-9-17 22:37:48
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  @-webkit-keyframes color-change-2x {
    0% {
      background: #19dcea
    }

    100% {
      background: #b22cff
    }
  }

  @keyframes color-change-2x {
    0% {
      background: #19dcea
    }

    100% {
      background: #b22cff
    }
  }

  /* animasi text judul */
  .tracking-in-contract {
    animation: tracking-in-contract 0.8s cubic-bezier(0.215, 0.610, 0.355, 1.000) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2022-9-17 23:21:41
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation tracking-in-contract
 * ----------------------------------------
 */
  @keyframes tracking-in-contract {
    0% {
      letter-spacing: 1em;
      opacity: 0;
    }

    40% {
      opacity: 0.6;
    }

    100% {
      letter-spacing: normal;
      opacity: 1;
    }
  }

  /* mobile */
  .judul {
    font-size: 24px;
  }

  /* clock */
  #clock,
  .tgl {
    color: azure;
    font-size: 11px;
    margin-left: auto;
    margin-right: 3px;
  }

  .wrapper {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
    justify-content: space-between;
  }

  footer section .bi {
    font-size: 14px;
  }

  footer .copyright {
    font-size: 12px;
  }


  /* desctop */

  @media (min-width: 992px) {

    .nav-link {
      text-transform: uppercase;
      margin-right: 10px;
      font-size: 15px;
    }

    nav span #clock {
      font-size: 10px;
    }

    .nav-link:hover::after {
      content: '';
      display: block;
      border-bottom: 3px solid white;
      width: 50%;
      margin: auto;
      padding-bottom: 5px;
      margin-bottom: -8px;
    }

    .navbar .tgl,
    .navbar #clock {
      font-size: 15px;
      margin-left: 3px;
    }

    body .wrapper .container h1 {
      font-size: 40px;
      color: #010101;
    }

    .icondesc {
      font-size: 25px;
    }

    .judul {
      font-size: 30px;
    }

    footer section .bi,
    footer .copyright {
      font-size: 20px;
    }

    footer section {
      margin-bottom: 3vh;
    }

    footer .container {
      padding-top: 3vh;
    }
  }
</style>